### ISSUE TITLE
iCal format

### ISSUE THREAD

**Issue by saizai** [voc/schedule#41] opened 2018-12-24 11:20 UTC
Could you please add iCal format for easy import?

Or a public Google Calendar address that's auto updated…

**Comment by saerdnaer** [comment] 2020-09-13 19:55
Duplicate of #38

**Closed by saerdnaer** 2020-09-13 19:55 UTC

**Comment by saizai** [comment] 2020-09-14 09:30
That's not the same format…

**Comment by saerdnaer** [comment] 2020-10-07 19:08
It is, the text of the issue is nearly 100% the same – but the other one was moved from another repository to this one.
