### ISSUE TITLE
Mixed time stamp offsets in <date> element in 35c3 in everything.schedule.xml

### ISSUE THREAD

**Issue by johnjohndoe** [voc/schedule#35] opened 2018-12-20 20:55 UTC
I noticed that the XML export (`everything.schedule.xml`) for 35c3 contains `<date>` elements with different time stamp offsets. The version of the file which I looked at contains both `+01:00` and `+00:00` time stamp offsets.

[`+01:00` example from 35C3 everything.schedule.xml:](https://github.com/voc/35C3_schedule/blob/7b6e051a397ca9762ec012bdfce28f14ecf3583d/everything.schedule.xml#L17)

``` xml
<date>2018-12-27T11:00:00+01:00</date>
```

[`+00:00` example from 35C3 everything.schedule.xml:](https://github.com/voc/35C3_schedule/blob/7b6e051a397ca9762ec012bdfce28f14ecf3583d/everything.schedule.xml#L2611)

``` xml
<date>2018-12-27T10:45:00+00:00</date>
```

I believe since all the event take place in the **same** conference location all the entries should share one time stamp offset.
This current mixed state is cumbersome to handle in the [EventFahrplan](https://github.com/EventFahrplan/EventFahrplan). Therefore, it would be great if you can **harmonize** the `<date>` values of all events.

---

/cc @chaoswest informed [here](https://twitter.com/tbsprs/status/1075858089889411073).

**Comment by a-tze** [comment] 2018-12-20 21:06
Just a side note (because I cannot verify if there is an actual error in the aggregated schedule after all):

  - events on a single conference do NOT always share the same timezone. Think of DST change. 
  - what you cite are offsets, not time zones. CET is a time zone, +01:00 is not.
  - please, do not take different offsets for different physical locations (though it would be extremely adorable for any datetime information in IT to be accompanied by a physical location like "Europe/Berlin" to make things easier)
  - this is in ISO format, that is handled by virtually any serious software or library. What kind of problems do actually emerge from this mix?

**Comment by saerdnaer** [comment] 2018-12-21 00:05
As of now EventFahrplan does the "parsing" of the iso date manually:

https://github.com/EventFahrplan/EventFahrplan/blob/545c22eadc54951d75c0bd00641c7e3660a3dcde/app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Lecture.java#L117-L128

I opened an downstream Issue about that: https://github.com/tuxmobil/CampFahrplan/issues/180 – but I will also look into how to solve that problem in this repo, tomorrow.

Sidenote: During refactoring I came across following part of datetime conversion code:
https://github.com/voc/schedule/blob/e8d28ee882aac9576fec161dbe2d474b0ca24061/wiki2schedule.py#L186-L188

where 
https://github.com/voc/schedule/blob/e8d28ee882aac9576fec161dbe2d474b0ca24061/wiki2schedule.py#L28

We should definitely check if the times from the wiki are correct and do not have an offset.

We also should check if https://github.com/voc/voctosched has already support for this date normalization feature or if it's easier to implement there... /cc: @zuntrax

**Comment by sandzwerg** [comment] 2018-12-23 21:45
Could someone check if this is still the case? I've asked the responsible people from chaos-west and they confirmed that this should be fixed. I would poke them again if this is still the case.

**Comment by johnjohndoe** [comment] 2018-12-24 12:33
@sandzwerg I checked the recent [`everything.schedule.xml`](https://github.com/voc/35C3_schedule/blob/bbd04418794100930a996321137b3e1354fc24e3/everything.schedule.xml), 24.12.2018, 1 PM GMT+1. The file contains only `+01:00` offsets. :+1: I think we can close this issue if nobody has a point to make. Thanks for fixing.

**Comment by sandzwerg** [comment] 2018-12-25 01:31
Sounds good to me, thanks for making us aware and for your work.

**Closed** 2018-12-25 08:02 UTC
